# Rename to dev version
# This is dev version
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "je_load_density_dev"
version = "0.0.53"
authors = [
    { name = "JE-Chen", email = "zenmailman@gmail.com" },
]
description = "Load & Stress Testing Freamework"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = [
        "locust"
]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/JE-Chen/LoadTesting"

[tool.setuptools.packages]
find = { namespaces = false }